version: "3"
services:
  jellyfin:
#    image: lscr.io/linuxserver/jellyfin:latest
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
#      - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - ./config:/config
#      - /path/to/tvseries:/data/tvshows
#      - /path/to/movies:/data/movies
      - /media/Films:/data/films
      - /media/Films_HERA:/data/films_hera
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
